name: Device Farm Test

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  device-farm-test:
    runs-on: ubuntu-latest
    steps:
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check APK exists
        run: ls -la *.apk
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Create Device Farm upload
        id: create-upload
        run: |
          UPLOAD_JSON=$(aws devicefarm create-upload \
            --project-arn "arn:aws:devicefarm:us-west-2:129896631391:project:768d5015-901f-4d96-b28d-0876cf3948bd" \
            --name "AWSDeviceFarmAndroidReferenceApp.apk" \
            --type ANDROID_APP)
          echo "upload_url=$(echo $UPLOAD_JSON | jq -r '.upload.url')" >> $GITHUB_OUTPUT
          echo "upload_arn=$(echo $UPLOAD_JSON | jq -r '.upload.arn')" >> $GITHUB_OUTPUT

      - name: Upload APK to Device Farm
        run: |
          curl -T "AWSDeviceFarmAndroidReferenceApp.apk" "${{ steps.create-upload.outputs.upload_url }}"

      - name: Wait for upload to process
        run: |
          STATUS="INITIALIZED"
          while [ "$STATUS" != "SUCCEEDED" ]; do
            if [ "$STATUS" == "FAILED" ]; then
              echo "Upload failed"
              exit 1
            fi
            sleep 5
            STATUS=$(aws devicefarm get-upload --arn "${{ steps.create-upload.outputs.upload_arn }}" | jq -r '.upload.status')
            echo "Status atual: $STATUS"
          done

      - name: Schedule Run
        run: |
          aws devicefarm schedule-run \
            --project-arn "arn:aws:devicefarm:us-west-2:129896631391:project:768d5015-901f-4d96-b28d-0876cf3948bd" \
            --app-arn "${{ steps.create-upload.outputs.upload_arn }}" \
            --device-pool-arn "arn:aws:devicefarm:us-west-2::devicepool:082d10e5-d7d7-48a5-ba5c-b33d66efa1f5" \
            --name "GitHub Actions Run - ${{ github.run_number }}"
